<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>RiseOverlay.UI</RootNamespace>
    <AssemblyName>RiseOverlay.UI</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RiseOverlay.Domain\RiseOverlay.Domain.csproj" />
  </ItemGroup>

</Project>
