<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>RiseOverlay.UI.Playground</RootNamespace>
    <AssemblyName>RiseOverlay.UI.Playground</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RiseOverlay.UI\RiseOverlay.UI.csproj" />
  </ItemGroup>

</Project>
